services:
  pomelo_llm:
    hostname: pomelo_llm
    user: server
    build: .
    env_file: .env
    expose:
      - '3000'
    networks:
      - default
    volumes:
      - ./cache:/home/server/.cache
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  webserver_pomelo_llm:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "2443:2443"
      - "2080:2080"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt/live/CHANGEMECHANGEME
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - pomelo_llm
    networks:
      - default 

networks:
  default:

volumes:
  certbot-etc:
  certbot-var:
  web-root:
