
const config = {
    paypalClientId: "AWzsggzP2HDuhQr7fpb6AiZPz3n-Xs9qhe0FuNOnRPJJ5Rh8yblLoLgvrG9WdFN5SpaPRiX10qY3Gq6S",
    paypalSubscriptionPlan: "P-6MD88519RX659384KM46OVZY",
    // baseURL: "https://api.pomeloprod.com:443",
    baseURL: "http://localhost:3080",
    login: "/api/login",
    register: "/api/register",
    userInfo: "/api/userdetails",
    getReports: "/api/report",
    getInsights: "/api/insights",
    postVerifyEmail: "/api/verifyemail",
    postResendEmail: "/api/resendemail",
    getNewToken: "/api/newtoken",
    forgotPassword: "/api/forgotpassword",
    resetPassword: "/api/resetpassword",
    getRules: "/api/rules",
    deleteRules: "/api/rules",
    putRule: "/api/rules",
    createOrder: "/api/create_order",
    captureOrder: "/api/capture_order",
    subscriptionDetails: "/api/subscription_status",
    cancelSubscription: "/api/cancel_subscription",
    deleteAccount: "/api/delete_account",
    getTimeWasted: "/api/time_wasted",
    getTimeWastingWebsites: "/api/time_wasting_websites",
    putTimeWastingWebsites: "/api/time_wasting_websites",
    deleteTimeWastingWebsites: "/api/time_wasting_websites",
};

export default config;