
export enum WebhookEvent
{
    CREATED = "BILLING.SUBSCRIPTION.CREATED",
    ACTIVATED = "BILLING.SUBSCRIPTION.ACTIVATED",
    UPDATED = "BILLING.SUBSCRIPTION.UPDATED",
    EXPIRED = "BILLING.SUBSCRIPTION.EXPIRED",
    CANCELLED = "BILLING.SUBSCRIPTION.CANCELLED",
    SUSPENDED = "BILLING.SUBSCRIPTION.SUSPENDED",
    PAYMENT_FAILED = "BILLING.SUBSCRIPTION.PAYMENT.FAILED",
};